name: Automatix Service Update

on:
  workflow_call:
    inputs:
      service:
        description: "The name of the service to update. If not set, no service update will be done in the product compose files. Default is empty"
        default: ""
        type: string
      url:
        description: "An image url pushed on harbor-os."
        type: string
        required: true
      tag:
        description: "An image tag pushed on harbor-os."
        type: string
        required: true
      digest:
        description: "An image digest pushed on harbor-os."
        type: string
      artifact-pattern:
        description: "Download the image digest as artifact. The image must be on harbor-os."
        type: string


    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      GREENBONE_REGISTRY:
        required: false
      GREENBONE_REGISTRY_USER:
        required: false
      GREENBONE_REGISTRY_TOKEN:
        required: false
      GREENBONE_REGISTRY_READ_USER:
        required: false
      GREENBONE_REGISTRY_READ_TOKEN:
        required: false
      GREENBONE_BOT_TOKEN:
        required: false

jobs:
  digest:
    if: inputs.service && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.settings.outputs.name }}
      url: ${{ steps.settings.outputs.url }}
      digest: ${{ steps.settings.outputs.digest }}
    steps:
      - name: Download digests
        if: inputs.artifact-pattern
        id: digests
        uses: greenbone/actions/download-digest@v3
        with:
          pattern: "march-digests${{ inputs.artifact-pattern && format('-{0}', inputs.artifact-pattern) || '' }}-*"

      - name: Set vars
        id: settings
        run: |
          echo "name=$(basename '${{ inputs.url }}')" >> $GITHUB_OUTPUT
          echo "url=$(echo '${{ inputs.url }}' | sed 's/^[^/]*\///')" >> $GITHUB_OUTPUT
          if [ '${{ inputs.artifact-pattern }}' ]; then
            echo "digest=${{ steps.digests.outputs.digests }}" >> $GITHUB_OUTPUT
          else
            echo "digest=${{ inputs.digest }}" >> $GITHUB_OUTPUT
          fi

  signing:
    if: inputs.service && startsWith(github.ref, 'refs/tags/v')
    needs: digest
    runs-on: self-hosted-generic-vm-amd64
    steps:
      - name: Login to Greenbone Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ vars.GREENBONE_REGISTRY }}
          username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

      - name: Container signing
        uses: greenbone/actions/container-signing@v3
        with:
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          cosign-tlog-upload: "false"
          image-tags: "${{ inputs.url }}:${{ inputs.tag }}"
          image-digest: ${{ needs.digest.outputs.digest }}

  sbom:
    if: inputs.service && startsWith(github.ref, 'refs/tags/v')
    needs: digest
    uses: greenbone/workflows/.github/workflows/generate-and-push-sbom-with-trivy-3rd-gen.yml@main
    with:
      image-url: "${{ inputs.url }}:${{ inputs.tag }}"
      image-registry-username-secret-name: "GREENBONE_REGISTRY_USER"
      image-registry-password-secret-name: "GREENBONE_REGISTRY_TOKEN"
      output-file-name: "${{ needs.digest.outputs.name }}.${{ inputs.tag }}.sbom.json"
      artifact-url: "${{ inputs.url }}-sbom:${{ inputs.tag }}"
    secrets: inherit

  automatix:
    if: inputs.service && startsWith(github.ref, 'refs/tags/v')
    needs: digest
    runs-on: ubuntu-latest
    steps:
      - name: Trigger product compose upgrade
        uses: greenbone/actions/trigger-workflow@v3
        with:
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          repository: "greenbone/automatix"
          workflow: "push.yml"
          inputs: '{"service": "${{ inputs.service }}", "image-url": "${{ needs.digest.outputs.url }}", "digest": "${{ needs.digest.outputs.digest }}", "version": "${{ inputs.tag }}"}'
