name: Detect hidden unicode

on:
  pull_request:

jobs:
  detect-hidden-unicode:
    runs-on: ubuntu-latest
    steps:
      - uses: greenbone/actions/detect-hidden-unicode@v3.35.4
        with:
          github-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
